sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/react-test -f Dockerfile.dev .

script:
  - docker run stephengrider/react-test npm test -- --coverage

after_sucess:
  - docker build -t stephengrider/react .

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-west-2"  
  app: "docker-react"
  env: "docker-react-dev"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker-react"
  on:
    branch: master
